### ISSUE TITLE
Username display

### ISSUE THREAD

**Issue by mattiasmucherie** [MLNProjects/SnakeCalendar#4]
Username should float RIGHT when in mobile view (works in Chrome but not Firefox)

**Comment by mattiasmucherie** [comment]
![Screenshot from 2019-03-10 00-59-45](https://user-images.githubusercontent.com/20210089/54078832-d7efef00-42cf-11e9-9f38-4c59033bd764.png)

**Comment by blondieboi** [comment]
var x = window.matchMedia("(max-width: 600px)")
    x.addListener(myFunction)

myFunction = (x)  => {
    if (x.matches) { 
      this.user = this.props.username
    } else {
      this.user = this.props.username[0]
    }

**Comment by blondieboi** [comment]
fixed
